-- Central image cache plus the mod-visible asset search path.  Every
-- renderer that used to call love.graphics.newImage(path) straight goes
-- through Assets.image, so an enabled mod shadows a generated asset with
-- its own file without editing a single record, and one flush() drops
-- every downstream cache for dev-mode hot reload.
--
-- No loader installed means resolve() is the identity, which is what
-- keeps a mod-free boot (and every headless test) loading exactly the
-- paths it always did.

local Assets = {}

-- resolved path -> love Image
local cache = {}
-- resolved (or asked-for) path -> builder for art that is not a file.
-- Game3ModWorld republishes Hoenn OW strips as tall stacked sheets so the
-- voxel billboard reader can walk frames downward the way Emerald's extract
-- already does. invalidate() keeps these; only the decoded Image cache drops.
local providers = {}
-- downstream caches that must empty when the search path changes
local invalidators = {}

-- The loader bridge: overrideOrder() yields mods highest-priority-first
-- and derivedPath(rel) yields an existing save/mod-derived/<id>/<rel>.
-- nil until the loader installs one.
Assets.loader = nil

local GENERATED = "assets/generated/"

local function exists(path)
  local fs = love and love.filesystem
  if not (fs and fs.getInfo) then return false end
  return fs.getInfo(path) ~= nil
end
Assets.exists = exists

-- an override dir shadows the generated cache; a transform's derived
-- output is the fallback under it, so hand-authored art beats generated
function Assets.resolve(path)
  local loader = Assets.loader
  if not loader or type(path) ~= "string" then return path end
  if path:sub(1, #GENERATED) ~= GENERATED then return path end
  local rel = path:sub(#GENERATED + 1)
  for _, mod in ipairs(loader:overrideOrder()) do
    local candidate = mod.path .. "/overrides/" .. rel
    if exists(candidate) then return candidate end
  end
  return loader:derivedPath(rel) or path
end

-- Last-resort art for a path that is not on disk.  Generated by the importer
-- alongside every other sheet; if even this is missing we fall back to a
-- blank 16x16 image built in memory so a bad path can never be fatal.
local MISSING_IMAGE = "assets/generated/sprites/placeholder_sprite.png"
local blankImage = nil

local function blank()
  if not blankImage then
    local data = love.image.newImageData(16, 16)
    blankImage = love.graphics.newImage(data)
  end
  return blankImage
end

-- A missing asset must degrade to visibly-wrong art, never to a thrown error.
-- love.graphics.newImage raises on a path PhysFS cannot open, and this is the
-- single choke point every renderer loads sheets through -- an unguarded raise
-- here propagates out of SpriteRenderer.new -> NPC.new -> the map build and
-- takes the whole map load down.
local function loadImage(resolved)
  local ok, image = pcall(love.graphics.newImage, resolved)
  if ok then return image end
  local Logger = require("src.core.Logger")
  Logger.warn("assets: missing image '%s' (using placeholder)", tostring(resolved))
  local fellBack, placeholder = pcall(love.graphics.newImage, Assets.resolve(MISSING_IMAGE))
  if fellBack then return placeholder end
  return blank()
end

function Assets.image(path)
  local resolved = Assets.resolve(path)
  local image = cache[resolved]
  if not image then
    image = loadImage(resolved)
    cache[resolved] = image
  end
  return image
end

-- pixel-level reads (tile-shift variants, the spinner strip blit) resolve
-- the same way but stay uncached: the caller keeps the derived product.
-- Same rule as Assets.image: a missing path degrades instead of raising.
function Assets.imageData(path)
  local resolved = Assets.resolve(path)
  local ok, data = pcall(love.image.newImageData, resolved)
  if ok then return data end
  local Logger = require("src.core.Logger")
  Logger.warn("assets: missing image data '%s' (using placeholder)", tostring(resolved))
  local fellBack, placeholder = pcall(love.image.newImageData, Assets.resolve(MISSING_IMAGE))
  if fellBack then return placeholder end
  return love.image.newImageData(16, 16)
end

function Assets.register(invalidate)
  invalidators[#invalidators + 1] = invalidate
end

-- hot reload's single entry point (20-developer-tooling): drop the central
-- cache and fan out to every registered downstream one.  A cache whose
-- invalidator throws must not strand the ones behind it in the list.
function Assets.invalidate()
  cache = {}
  for _, fn in ipairs(invalidators) do pcall(fn) end
end

Assets.flush = Assets.invalidate

-- Loader:load hands over the live mod set once the merge is done.  Load
-- order is priority ascending, so the search walks it backwards: the mod
-- that wins the record merge wins the asset lookup too.
function Assets.installLoader(loader)
  if not loader then
    Assets.loader = nil
    Assets.invalidate()
    return
  end
  local bridge = {}
  function bridge:overrideOrder()
    local order = {}
    local loaded = loader.loaded or {}
    for i = #loaded, 1, -1 do
      order[#order + 1] = { id = loaded[i].manifest.id, path = loaded[i].path }
    end
    return order
  end
  function bridge:derivedPath(rel)
    for _, mod in ipairs(self:overrideOrder()) do
      local candidate = "save/mod-derived/" .. mod.id .. "/" .. rel
      if exists(candidate) then return candidate end
    end
    return nil
  end
  Assets.loader = bridge
  Assets.invalidate()
end

return Assets
