-- Polished Crystal's script command table: 224 commands where
-- Gold/Crystal have ~120, renumbered from index 3 onward -- so a
-- Polished Crystal script read with Crystal's table desyncs on the
-- first shifted opcode and never recovers.
--
-- GENERATED by tools/gen_polished_ops.py.  Names and operand widths
-- come from the disassembly's macros/scripts/events.asm, where each
-- MACRO body is literally what the assembler emits; the terminator
-- list is derived from engine/overworld/scripting.asm by following
-- each handler to StopScript/ScriptJump rather than from the command
-- NAMES, which lie both ways here (`iffalse_jumptext` falls through,
-- `fruittree` never returns).  Do not hand-edit: regenerate.
Gen2ScriptOps.COMMANDS_POLISHED = {
  { "scall", "p" }, { "farscall", "f" }, { "memcall", "p" }, -- 00
  { "sjump", "p" }, { "farsjump", "f" }, { "memjump", "p" }, -- 03
  { "ifequal", "bp" }, { "ifnotequal", "bp" }, { "iffalse", "p" }, -- 06
  { "iftrue", "p" }, { "ifgreater", "bp" }, { "ifless", "bp" }, -- 09
  { "jumpstd", "b" }, { "callstd", "b" }, { "callasm", "f" }, -- 0C
  { "special", "b" }, { "memcallasm", "w" }, { "checkmapscene", "" }, -- 0F
  { "setmapscene", "b" }, { "checkscene", "" }, { "setscene", "b" }, -- 12
  { "setval", "b" }, { "setval16", "w" }, { "addval", "b" }, -- 15
  { "random", "b" }, { "random16", "w" }, { "readmem", "w" }, -- 18
  { "readmem16", "ww" }, { "writemem", "w" }, { "loadmem", "wb" }, -- 1B
  { "readvar", "b" }, { "writevar", "b" }, { "loadvar", "bb" }, -- 1E
  { "giveitem", "bbb" }, { "takeitem", "bbb" }, { "checkitem", "b" }, -- 21
  { "givemoney", "bm" }, { "takemoney", "bm" }, { "checkmoney", "bm" }, -- 24
  { "givecoins", "w" }, { "takecoins", "w" }, { "checkcoins", "w" }, -- 27
  { "addcellnum", "b" }, { "delcellnum", "b" }, { "checkcellnum", "b" }, -- 2A
  { "checktime", "b" }, { "checkpoke", "" }, { "givepoke", "bbbbbbbbbppb" }, -- 2D
  { "giveegg", "" }, { "givepokemail", "p" }, { "checkpokemail", "p" }, -- 30
  { "checkevent", "w" }, { "clearevent", "w" }, { "setevent", "w" }, -- 33
  { "checkflag", "w" }, { "clearflag", "w" }, { "setflag", "w" }, -- 36
  { "wildon", "" }, { "wildoff", "" }, { "warpmod", "b" }, -- 39
  { "blackoutmod", "" }, { "warp", "bb" }, { "getmoney", "bb" }, -- 3C
  { "getcoins", "b" }, { "getnum", "b" }, { "getmonname", "b" }, -- 3F
  { "getitemname", "bb" }, { "getcurlandmarkname", "b" }, { "gettrainername", "bbb" }, -- 42
  { "getstring", "tb" }, { "itemnotify", "" }, { "pocketisfull", "" }, -- 45
  { "opentext", "" }, { "reanchormap", "" }, { "closetext", "" }, -- 48
  { "farwritetext", "f" }, { "writetext", "t" }, { "repeattext", "" }, -- 4B
  { "yesorno", "" }, { "loadmenu", "M" }, { "closewindow", "" }, -- 4E
  { "jumptextfaceplayer", "t" }, { "farjumptext", "f" }, { "jumptext", "t" }, -- 51
  { "waitbutton", "" }, { "promptbutton", "" }, { "pokepic", "b" }, -- 54
  { "closepokepic", "" }, { "_2dmenu", "" }, { "verticalmenu", "" }, -- 57
  { "randomwildmon", "" }, { "loadtemptrainer", "" }, { "loadwildmon", "bb" }, -- 5A
  { "loadtrainer", "bb" }, { "startbattle", "" }, { "reloadmapafterbattle", "" }, -- 5D
  { "catchtutorial", "b" }, { "trainertext", "b" }, { "trainerflagaction", "b" }, -- 60
  { "winlosstext", "tt" }, { "scripttalkafter", "" }, { "endifjustbattled", "" }, -- 63
  { "checkjustbattled", "" }, { "setlasttalked", "b" }, { "applymovement", "bM" }, -- 66
  { "applymovementlasttalked", "M" }, { "faceplayer", "" }, { "faceobject", "bb" }, -- 69
  { "variablesprite", "bb" }, { "disappear", "b" }, { "appear", "b" }, -- 6C
  { "follow", "bb" }, { "stopfollow", "" }, { "moveobject", "bbb" }, -- 6F
  { "writeobjectxy", "b" }, { "loademote", "b" }, { "showemote", "bbb" }, -- 72
  { "turnobject", "bb" }, { "follownotexact", "bb" }, { "earthquake", "b" }, -- 75
  { "changemapblocks", "f" }, { "changeblock", "bbb" }, { "reloadmap", "" }, -- 78
  { "refreshmap", "" }, { "usestonetable", "p" }, { "playmusic", "b" }, -- 7B
  { "encountermusic", "" }, { "musicfadeout", "bb" }, { "playmapmusic", "" }, -- 7E
  { "dontrestartmapmusic", "" }, { "cry", "b" }, { "playsound", "b" }, -- 81
  { "waitsfx", "" }, { "warpsound", "" }, { "specialsound", "" }, -- 84
  { "autoinput", "b" }, { "newloadmap", "b" }, { "pause", "b" }, -- 87
  { "deactivatefacing", "b" }, { "sdefer", "p" }, { "warpcheck", "" }, -- 8A
  { "stopandsjump", "p" }, { "endcallback", "" }, { "end", "" }, -- 8D
  { "reloadend", "b" }, { "endall", "" }, { "pokemart", "bb" }, -- 90
  { "elevator", "p" }, { "trade", "b" }, { "askforphonenumber", "b" }, -- 93
  { "hangup", "" }, { "describedecoration", "b" }, { "fruittree", "bb" }, -- 96
  { "specialphonecall", "b" }, { "checkphonecall", "" }, { "verbosegiveitem", "bbb" }, -- 99
  { "verbosegiveitemvar", "bb" }, { "swarm", "b" }, { "halloffame", "" }, -- 9C
  { "credits", "" }, { "warpfacing", "bbb" }, { "battletowertext", "b" }, -- 9F
  { "getlandmarkname", "bb" }, { "gettrainerclassname", "bb" }, { "wait", "b" }, -- A2
  { "checksave", "" }, { "trainerpic", "b" }, { "givetmhm", "b" }, -- A5
  { "checktmhm", "b" }, { "verbosegivetmhm", "b" }, { "tmhmnotify", "" }, -- A8
  { "gettmhmname", "bb" }, { "checkdarkness", "" }, { "checkunits", "" }, -- AB
  { "unowntypeface", "" }, { "restoretypeface", "" }, { "jumpstashedtext", "" }, -- AE
  { "jumpopenedtext", "t" }, { "iftrue_jumptext", "t" }, { "iffalse_jumptext", "t" }, -- B1
  { "iftrue_jumptextfaceplayer", "t" }, { "iffalse_jumptextfaceplayer", "t" }, { "iftrue_jumpopenedtext", "t" }, -- B4
  { "iffalse_jumpopenedtext", "t" }, { "writethistext", "" }, { "jumpthistext", "" }, -- B7
  { "jumpthistextfaceplayer", "" }, { "jumpthisopenedtext", "" }, { "showtext", "t" }, -- BA
  { "showtextfaceplayer", "t" }, { "applyonemovement", "bbb" }, { "showcrytext", "t" }, -- BD
  { "endtext", "" }, { "waitendtext", "" }, { "iftrue_endtext", "" }, -- C0
  { "iffalse_endtext", "" }, { "loadgrottomon", "" }, { "giveapricorn", "bbb" }, -- C3
  { "paintingpic", "b" }, { "checkegg", "" }, { "givekeyitem", "b" }, -- C6
  { "checkkeyitem", "b" }, { "takekeyitem", "b" }, { "verbosegivekeyitem", "b" }, -- C9
  { "keyitemnotify", "" }, { "givebp", "w" }, { "takebp", "w" }, -- CC
  { "checkbp", "w" }, { "sjumpfwd", "b" }, { "ifequalfwd", "bb" }, -- CF
  { "iffalsefwd", "b" }, { "iftruefwd", "b" }, { "scalltable", "p" }, -- D2
  { "setmapobjectmovedata", "bb" }, { "setmapobjectpal", "bb" }, { "givespecialitem", "b" }, -- D5
  { "givebadge", "b" }, { "setquantity", "" }, { "pluralize", "p" }, -- D8
  { "loadtrainerwithpal", "bbb" }, { "nooryes", "" }, { "digmod", "b" }, -- DB
  { "toggleevent", "w" }, { "usepaletteswap", "p" }, -- DE
}

Gen2ScriptOps.TERMINATORS_POLISHED = {
  ["credits"] = true, ["describedecoration"] = true, ["end"] = true, ["endall"] = true,
  ["endcallback"] = true, ["endtext"] = true, ["farjumptext"] = true, ["farsjump"] = true,
  ["fruittree"] = true, ["halloffame"] = true, ["jumpopenedtext"] = true, ["jumpstashedtext"] = true,
  ["jumpstd"] = true, ["jumptext"] = true, ["jumptextfaceplayer"] = true, ["jumpthisopenedtext"] = true,
  ["jumpthistext"] = true, ["jumpthistextfaceplayer"] = true, ["memjump"] = true, ["pokemart"] = true,
  ["reloadend"] = true, ["reloadmapafterbattle"] = true, ["scripttalkafter"] = true, ["sjump"] = true,
  ["sjumpfwd"] = true, ["stopandsjump"] = true, ["trade"] = true, ["waitendtext"] = true,
}
