-- Prism's ScriptCommandTable (engine/scripting.asm): 236 commands where
-- Gold/Crystal have ~120, diverging from index 13 onward -- so a Prism
-- script read with Crystal's table desyncs on the first shifted opcode
-- and never recovers.
--
-- GENERATED by tools/gen_prism_ops.py from the Prism disassembly's own
-- macros/event.asm.  `enum <name>_command` gives the order and each
-- MACRO body gives the exact bytes the assembler emits, so these widths
-- are the encoder's, not an inference from handler control flow.  Do not
-- hand-edit: regenerate.
Gen2ScriptOps.COMMANDS_PRISM = {
  { "scall", "p" }, { "farscall", "f" }, { "ptcall", "d" }, -- 00
  { "jump", "p" }, { "farjump", "f" }, { "ptjump", "d" }, -- 03
  { "if_equal", "bp" }, { "if_not_equal", "bp" }, { "iffalse", "p" }, -- 06
  { "iftrue", "p" }, { "if_greater_than", "bp" }, { "if_less_than", "bp" }, -- 09
  { "jumpstd", "b" }, { "fieldmovepokepic", "" }, { "callasm", "D" }, -- 0C
  { "special", "b" }, { "ptcallasm", "w" }, { "checkmaptriggers", "bb" }, -- 0F
  { "domaptrigger", "bbb" }, { "checktriggers", "" }, { "dotrigger", "b" }, -- 12
  { "writebyte", "b" }, { "addvar", "b" }, { "random", "bb" }, -- 15
  { "readarrayhalfword", "b" }, { "copybytetovar", "w" }, { "copyvartobyte", "w" }, -- 18
  { "loadvar", "wb" }, { "checkcode", "b" }, { "writevarcode", "b" }, -- 1B
  { "writecode", "bb" }, { "giveitem", "bb" }, { "takeitem", "bb" }, -- 1E
  { "checkitem", "b" }, { "givemoney", "bm" }, { "takemoney", "bm" }, -- 21
  { "checkmoney", "bm" }, { "givecoins", "w" }, { "takecoins", "w" }, -- 24
  { "checkcoins", "w" }, { "writehalfword", "w" }, { "pushhalfword", "w" }, -- 27
  { "pushhalfwordvar", "" }, { "checktime", "b" }, { "checkpoke", "b" }, -- 2A
  { "givepoke", "bbbbww" }, { "giveegg", "bb" }, { "copyhalfwordvartovar", "" }, -- 2D
  { "copyvartohalfwordvar", "" }, { "checkevent", "w" }, { "clearevent", "w" }, -- 30
  { "setevent", "w" }, { "checkflag", "w" }, { "clearflag", "w" }, -- 33
  { "setflag", "w" }, { "wildon", "" }, { "wildoff", "" }, -- 36
  { "warpmod", "bbb" }, { "blackoutmod", "bb" }, { "warp", "bbbb" }, -- 39
  { "readmoney", "bb" }, { "readcoins", "b" }, { "variablestablerandom", "bb" }, -- 3C
  { "pokenamemem", "bb" }, { "itemtotext", "bb" }, { "mapnametotext", "b" }, -- 3F
  { "trainertotext", "bbb" }, { "stringtotext", "wb" }, { "itemnotify", "" }, -- 42
  { "pocketisfull", "" }, { "opentext", "" }, { "refreshscreen", "" }, -- 45
  { "closetext", "" }, { "cmdwitharrayargs", "b" }, { "farwritetext", "T" }, -- 48
  { "writetext", "t" }, { "repeattext", "" }, { "yesorno", "" }, -- 4B
  { "loadmenudata", "w" }, { "closewindow", "" }, { "jumptextfaceplayer", "t" }, -- 4E
  { "farjumptext", "T" }, { "jumptext", "t" }, { "waitbutton", "" }, -- 51
  { "buttonsound", "" }, { "pokepic", "b" }, { "closepokepic", "" }, -- 54
  { "eventvarop", "" }, { "verticalmenu", "" }, { "scrollingmenu", "b" }, -- 57
  { "randomwildmon", "" }, { "loadmemtrainer", "" }, { "loadwildmon", "bbbbb" }, -- 5A
  { "loadtrainer", "bb" }, { "startbattle", "" }, { "reloadmapafterbattle", "" }, -- 5D
  { "addhalfwordtovar", "w" }, { "trainertext", "b" }, { "trainerflagaction", "b" }, -- 60
  { "winlosstext", "tt" }, { "scripttalkafter", "" }, { "end_if_just_battled", "" }, -- 63
  { "check_just_battled", "" }, { "setlasttalked", "b" }, { "applymovement", "bM" }, -- 66
  { "applymovement2", "M" }, { "faceplayer", "" }, { "faceperson", "bb" }, -- 69
  { "variablesprite", "bb" }, { "disappear", "b" }, { "appear", "b" }, -- 6C
  { "follow", "bb" }, { "stopfollow", "" }, { "moveperson", "bbb" }, -- 6F
  { "writepersonxy", "b" }, { "loademote", "b" }, { "showemote", "bbbbb" }, -- 72
  { "spriteface", "bb" }, { "follownotexact", "bb" }, { "earthquake", "b" }, -- 75
  { "changemap", "bw" }, { "changeblock", "bbb" }, { "reloadmap", "" }, -- 78
  { "reloadmappart", "" }, { "writecmdqueue", "w" }, { "delcmdqueue", "b" }, -- 7B
  { "playmusic", "w" }, { "encountermusic", "" }, { "musicfadeout", "wb" }, -- 7E
  { "playmapmusic", "" }, { "dontrestartmapmusic", "" }, { "cry", "b" }, -- 81
  { "playsound", "w" }, { "waitsfx", "" }, { "warpsound", "" }, -- 84
  { "copyvarbytetovar", "" }, { "newloadmap", "b" }, { "pause", "b" }, -- 87
  { "deactivatefacing", "b" }, { "priorityjump", "p" }, { "warpcheck", "" }, -- 8A
  { "ptpriorityjump", "p" }, { "return", "" }, { "end", "" }, -- 8D
  { "reloadandreturn", "b" }, { "end_all", "" }, { "pokemart", "bb" }, -- 90
  { "elevator", "w" }, { "scriptstartasmf", "" }, { "pophalfwordvar", "" }, -- 93
  { "unused_96", "" }, { "unused_97", "" }, { "pushbyte", "b" }, -- 96
  { "fruittree", "b" }, { "swapbyte", "b" }, { "loadarray", "wb" }, -- 99
  { "verbosegiveitem", "bb" }, { "verbosegiveitem2", "bb" }, { "swarm", "bbb" }, -- 9C
  { "killsfx", "" }, { "checkiteminbox", "b" }, { "warpfacing", "bbbbb" }, -- 9F
  { "battletowertext", "b" }, { "landmarktotext", "bb" }, { "trainerclassname", "bb" }, -- A2
  { "name", "bbb" }, { "wait", "b" }, { "loadscrollingmenudata", "w" }, -- A5
  { "backupcustchar", "" }, { "restorecustchar", "" }, { "addhalfwordvartovar", "" }, -- A8
  { "addhalfwordtohalfwordvar", "w" }, { "givecraftingEXP", "b" }, { "copybytetohalfwordvar", "w" }, -- AB
  { "givetm", "b" }, { "unused_AF", "" }, { "itemplural", "b" }, -- AE
  { "pullvar", "" }, { "setplayersprite", "b" }, { "setplayercolor", "bb" }, -- B1
  { "loadsignpost", "ww" }, { "checkpokemontype", "b" }, { "isinarray", "wwbb" }, -- B4
  { "pusharray", "" }, { "poparray", "" }, { "startmirrorbattle", "" }, -- B7
  { "comparevartobyte", "w" }, { "backupsecondpokemon", "" }, { "restoresecondpokemon", "" }, -- BA
  { "loadhalfwordvar", "b" }, { "pullhalfwordvar", "" }, { "divideby", "b" }, -- BD
  { "isinsingulararray", "w" }, { "getnthstring", "wb" }, { "readpersonxy", "bw" }, -- C0
  { "return_if_callback_else_end", "" }, { "copy", "wbb" }, { "switch", "b" }, -- C3
  { "multiplyvar", "b" }, { "seteventvar", "b" }, { "callasmf", "D" }, -- C6
  { "jumptable", "d" }, { "anonjumptable", "" }, { "varblocks", "w" }, -- C9
  { "addbytetovar", "w" }, { "paragraphdelay", "" }, { "playwaitsfx", "w" }, -- CC
  { "scriptstartasm", "" }, { "copystring", "b" }, { "endtext", "" }, -- CF
  { "pushvar", "" }, { "popvar", "" }, { "swapvar", "" }, -- D2
  { "getweekday", "" }, { "toggle", "www" }, { "unused_D7", "" }, -- D5
  { "selse", "" }, { "sendif", "" }, { "siffalse", "" }, -- D8
  { "siftrue", "" }, { "sifgt", "b" }, { "siflt", "b" }, -- DB
  { "sifeq", "b" }, { "sifne", "b" }, { "readarray", "b" }, -- DE
  { "givetmnomessage", "b" }, { "findpokemontype", "b" }, { "startpokeonly", "bbb" }, -- E1
  { "endpokeonly", "bbb" }, { "fadetomapmusic", "b" }, { "menuanonjumptable", "w" }, -- E4
  { "modifyeventvar", "b" }, { "showtext", "t" }, { "closetextend", "" }, -- E7
  { "toggleevent", "w" }, { "getpartymonname", "b" }, -- EA
}

-- Macros whose byte count depends on their argument count (`if _NARG`).
-- The first branch is what the table above encodes; these are the ones
-- to check by hand if a script desyncs at one of them:
--   callasm
--   giveitem
--   takeitem
--   givepoke
--   farwritetext
--   farjumptext
--   loadwildmon
--   loadarray
--   verbosegiveitem
--   setplayercolor
--   loadsignpost
--   seteventvar
--   callasmf
--   toggle

-- Commands after which the interpreter never reads the next byte:
-- the handler either stops the script or UNCONDITIONALLY rewrites the
-- script pointer.  Derived from engine/scripting.asm by following only
-- plain jp/jr and fallthrough -- `if_equal` reaches ScriptJump too, but
-- through `jr z`, and its other arm falls through, so it is not one.
--
-- A terminator the walker does not know is what runs it off the end of a
-- script into whatever follows, which is where every remaining desync
-- came from: the failing opcode was always >= 236, i.e. past the end of
-- the table, so it had never been a command at all.
Gen2ScriptOps.TERMINATORS_PRISM = {
  anonjumptable = true, closetextend = true, ["end"] = true, end_all = true,
  endtext = true, farjump = true, farjumptext = true, fruittree = true,
  jump = true, jumpstd = true, jumptext = true, jumptextfaceplayer = true,
  loadsignpost = true, menuanonjumptable = true, pokemart = true, ptjump = true,
  ptpriorityjump = true, reloadandreturn = true, ["return"] = true, return_if_callback_else_end = true,
  scriptstartasmf = true, scripttalkafter = true,
}
