from pathlib import Path
root=Path(__file__).resolve().parents[1]
checks=[]
def ck(cond,msg): checks.append((bool(cond),msg)); print(('PASS ' if cond else 'FAIL ')+msg)
settings=(root/'lib/Settings.lua').read_text()
tornado=(root/'lib/Tornado.lua').read_text()
config=(root/'lib/Config.lua').read_text()
snow=(root/'lib/SnowPack.lua').read_text()
paint=(root/'lib/SnowSurfacePaint.lua').read_text()
atmos=(root/'lib/DramalessAtmos.lua').read_text()
cel=(root/'lib/CelestialBodies.lua').read_text()
cr2=(root/'lib/CelestialRenderer2.lua').read_text()
ck('label = "TORNADO FREQUENCY"' in settings,'player menu exposes TORNADO FREQUENCY')
ck('{ "EXTREME", "extreme" }' in settings,'tornado frequency exposes an increased EXTREME rate')
ck('rare=180,normal=90,often=60,extreme=30' in config,'frequency ladder maps to 180/90/60/30 second opportunities')
ck('math.max(30,tonumber(c.everySeconds) or 90)' in tornado,'2D Gale no longer clamps tornado opportunities to 120 seconds')
ck('T._legacyTimer=T._legacyTimer-every' in tornado,'2D Gale preserves cadence remainder instead of discarding time')
ck('key = "celestialRendering"' in settings and 'label = "CELESTIAL RENDERING"' in settings,'in-game celestial rendering option exists')
ck('function Settings.use3dCelestial()' in settings,'settings expose independent 3D celestial authority')
ck('elseif Atmos._drawing and celestialWorldWanted() then' in atmos,'2D weather can still execute world-space celestial draw')
ck('return Atmos.active() and celestialWorldWanted()' in atmos,'3D celestial ownership is independent from weather presentation')
ck('NS.projectDirection' in cel and 'Voxel3D' in cel,'2D sun/moon projection consumes the real voxel camera basis')
ck('DA.voxel3d' in cr2,'2D celestial facade receives active voxel camera state')
ck('hostVoxelScene.groundAt' in snow and 'ctx.fallbackGroundY=fallback' in snow,'SnowPack derives fallback floor from exact voxel player support')
ck('s.a >= 0.30' in paint and 'Raised/ledge geometry' in paint,'depth repaint explicitly covers cinematic ledges')
ck('usePhysicalBank' in paint,'raised scenery remains repaint-only instead of detached snow caps')
print(f'8.1.67 structural contract: {sum(x for x,_ in checks)}/{len(checks)} passed')
raise SystemExit(0 if all(x for x,_ in checks) else 1)
