-- Generated by tools/build_data.py. DO NOT EDIT.
-- Source: Gen2 Phase 2B symbol-derived trainer text scaffold
return {
  AZALEA_GYM = {
    [1] = {
      after = "AzaleaGymBugsyScript.AfterText",
      battle = "AzaleaGymBugsyScript.SeenText",
      range = 0,
      won = "AzaleaGymBugsyScript.BeatenText",
    },
  },
  AZALEA_TOWN = {
    [1] = {
      after = "AzaleaTownRivalBattleTrigger2.AfterText",
      battle = "AzaleaTownRivalBattleTrigger2.SeenText",
      range = 0,
      won = "AzaleaTownRivalBattleTrigger2.WinText",
    },
  },
  BELLCHIME_TRAIL = {
    [1] = {
      battle = "BellchimeTrailValerieScript.BattleText",
      range = 0,
      won = "BellchimeTrailValerieScript.BeatenText",
    },
  },
  BILLS_HOUSE = {
    [1] = {
      after = "BillsHouseBillScript.AfterText",
      battle = "BillsHouseBillScript.SeenText",
      range = 0,
      won = "BillsHouseBillScript.BeatenText",
    },
  },
  CELADON_GAME_CORNER = {
    [1] = {
      after = "CeladonGameCornerRichBoyTobin.AfterText",
      battle = "CeladonGameCornerRichBoyTobin.SeenText",
      range = 0,
      won = "CeladonGameCornerRichBoyTobin.BeatenText",
    },
  },
  CELADON_UNIVERSITY_CAFETERIA = {
    [1] = {
      battle = "CeladonUniversityCafeteriaCoreyScript.SeenText",
      range = 0,
      won = "CeladonUniversityCafeteriaCoreyScript.BeatenText",
    },
  },
  CELADON_UNIVERSITY_CLASSROOM4 = {
    [1] = {
      battle = "CeladonUniversityClassroom4RaymondScript.SeenText",
      range = 0,
      won = "CeladonUniversityClassroom4RaymondScript.BeatenText",
    },
  },
  CELADON_UNIVERSITY_LOUNGE = {
    [1] = {
      battle = "CeladonUniversityLoungeNeeshaScript.SeenText",
      range = 0,
      won = "CeladonUniversityLoungeNeeshaScript.BeatenText",
    },
  },
  CELADON_UNIVERSITY_POOL = {
    [1] = {
      battle = "CeladonUniversityPoolFergusScript.SeenText",
      range = 0,
      won = "CeladonUniversityPoolFergusScript.BeatenText",
    },
  },
  ECRUTEAK_SHRINE_INSIDE = {
    [1] = {
      battle = "EcruteakShrineInsideReiBattleText",
      range = 0,
      won = "EcruteakShrineInsideReiBeatenText",
    },
  },
  MURKY_SWAMP = {
    [1] = {
      after = "MurkySwampNurseBeatriceScript.AfterText",
      battle = "MurkySwampNurseBeatriceScript.SeenText",
      range = 0,
      won = "MurkySwampNurseBeatriceScript.BeatenText",
    },
  },
  OLIVINE_LIGHTHOUSE3_F = {
    [1] = {
      battle = "OlivineLighthouse3FBattleGirlEmy.SeenText",
      range = 0,
      won = "OlivineLighthouse3FBattleGirlEmy.BeatenText",
    },
  },
  QUIET_CAVE_B1_F = {
    [1] = {
      after = "QuietCaveB1FNurseKeikoScript.AfterText",
      battle = "QuietCaveB1FNurseKeikoScript.SeenText",
      range = 0,
      won = "QuietCaveB1FNurseKeikoScript.BeatenText",
    },
  },
  RADIO_TOWER5_F = {
    [1] = {
      after = "RadioTower5FRocketBossAfterText",
      battle = "RadioTower5FRocketBossBeforeText",
      range = 0,
      won = "RadioTower5FRocketBossWinText",
    },
  },
  ROCKET_HIDEOUT_B1_F = {
    [1] = {
      battle = "RocketHideoutB1FBattleGirlSasha.SeenText",
      range = 0,
      won = "RocketHideoutB1FBattleGirlSasha.BeatenText",
    },
    [2] = {
      after = "RocketHideoutB1FBlackBeltRylan.AfterText",
      battle = "RocketHideoutB1FBlackBeltRylan.SeenText",
      range = 0,
      won = "RocketHideoutB1FBlackBeltRylan.BeatenText",
    },
    [3] = {
      battle = "RocketHideoutB1FLassMavis.SeenText",
      range = 0,
      won = "RocketHideoutB1FLassMavis.BeatenText",
    },
    [4] = {
      battle = "RocketHideoutB1FPicnickerZane.SeenText",
      range = 0,
      won = "RocketHideoutB1FPicnickerZane.BeatenText",
    },
    [5] = {
      battle = "RocketHideoutB1FScientistSanders.SeenText",
      range = 0,
      won = "RocketHideoutB1FScientistSanders.BeatenText",
    },
  },
  ROCKET_HIDEOUT_B2_F = {
    [1] = {
      battle = "RocketHideoutB2FHexManiacCoryn.SeenText",
      range = 0,
      won = "RocketHideoutB2FHexManiacCoryn.BeatenText",
    },
  },
  ROCKET_HIDEOUT_B3_F = {
    [1] = {
      battle = "RocketHideoutB3FCoolDudeDaric.SeenText",
      range = 0,
      won = "RocketHideoutB3FCoolDudeDaric.BeatenText",
    },
    [2] = {
      battle = "RocketHideoutB3FCosplayerLyric.SeenText",
      range = 0,
      won = "RocketHideoutB3FCosplayerLyric.BeatenText",
    },
  },
  ROCKET_HIDEOUT_B4_F = {
    [1] = {
      battle = "RocketHideoutB4FBlancheScript.SeenText",
      range = 0,
      won = "RocketHideoutB4FBlancheScript.BeatenText",
    },
    [2] = {
      battle = "RocketHideoutB4FCandelaScript.SeenText",
      range = 0,
      won = "RocketHideoutB4FCandelaScript.BeatenText",
    },
    [3] = {
      battle = "RocketHideoutB4FSparkScript.SeenText",
      range = 0,
      won = "RocketHideoutB4FSparkScript.BeatenText",
    },
    [4] = {
      after = "RocketHideoutB4FSuperNerdNolan.AfterText",
      battle = "RocketHideoutB4FSuperNerdNolan.SeenText",
      range = 0,
      won = "RocketHideoutB4FSuperNerdNolan.BeatenText",
    },
    [5] = {
      after = "RocketHideoutB4FTeacherSerena.AfterText",
      battle = "RocketHideoutB4FTeacherSerena.SeenText",
      range = 0,
      won = "RocketHideoutB4FTeacherSerena.BeatenText",
    },
  },
  ROUTE19_BEACH_HOUSE = {
    [1] = {
      after = "Route19BeachHouseVictorScript.AfterText",
      battle = "Route19BeachHouseVictorScript.SeenText",
      range = 0,
      won = "Route19BeachHouseVictorScript.BeatenText",
    },
  },
  ROUTE24 = {
    [1] = {
      battle = "Route24RocketSeenText",
      range = 0,
      won = "Route24RocketBeatenText",
    },
  },
  ROUTE27 = {
    [1] = {
      battle = "Route27VeteranfScript.SeenText",
      range = 0,
      won = "Route27VeteranfScript.BeatenText",
    },
  },
  ROUTE32 = {
    [1] = {
      battle = "Route32CooltrainerMTrigger.SeenText",
      range = 0,
      won = "Route32CooltrainerMTrigger.BeatenText",
    },
  },
  ROUTE34 = {
    [1] = {
      battle = "Route34RichBoyIrvingScript.SeenText",
      range = 0,
      won = "Route34RichBoyIrvingScript.BeatenText",
    },
  },
  ROUTE36 = {
    [1] = {
      battle = "Route36CooltrainerfChiaraScript.SeenText",
      range = 0,
      won = "Route36CooltrainerfChiaraScript.BeatenText",
    },
  },
  ROUTE39 = {
    [1] = {
      battle = "Route39CowgirlAnnieScript.SeenText",
      range = 0,
      won = "Route39CowgirlAnnieScript.BeatenText",
    },
  },
  ROUTE41 = {
    [1] = {
      after = "Route41MarlonScript.AfterText",
      battle = "Route41MarlonScript.SeenText",
      range = 0,
      won = "Route41MarlonScript.BeatenText",
    },
  },
  ROUTE43 = {
    [1] = {
      battle = "Route43SightseerfScript.SeenText",
      range = 0,
      won = "Route43SightseerfScript.BeatenText",
    },
  },
  ROUTE44 = {
    [1] = {
      battle = "Route44VeteranmScript.SeenText",
      range = 0,
      won = "Route44VeteranmScript.BeatenText",
    },
  },
  ROUTE45 = {
    [1] = {
      battle = "Route45Dragon_tamerScript.SeenText",
      range = 0,
      won = "Route45Dragon_tamerScript.BeatenText",
    },
  },
  ROUTE48 = {
    [1] = {
      after = "Route48JessieJamesAfterText",
      battle = "Route48JessieJamesSeenText",
      range = 0,
      won = "Route48JessieJamesBeatenText",
    },
  },
  SAFARI_ZONE_WEST_REST_HOUSE2 = {
    [1] = {
      after = "SafariZoneWestRestHouse2FlanneryScript.AfterText",
      battle = "SafariZoneWestRestHouse2FlanneryScript.SeenText",
      range = 0,
      won = "SafariZoneWestRestHouse2FlanneryScript.BeatenText",
    },
  },
  SHAMOUTI_SHRINE_RUINS = {
    [1] = {
      after = "ShamoutiShrineRuinsLawrenceScript.AfterText",
      battle = "ShamoutiShrineRuinsLawrenceScript.SeenText",
      range = 0,
      won = "ShamoutiShrineRuinsLawrenceScript.BeatenText",
    },
  },
  TRAINER_HOUSE_B1_F = {
    [1] = {
      battle = "TrainerHouseB1FOpponentBeforeText",
      range = 0,
      won = "TrainerHouseB1FOpponentBeatenText",
    },
  },
  UNDERGROUND = {
    [1] = {
      after = "UndergroundRivalAfterText",
      battle = "UndergroundRivalBeforeText",
      range = 0,
      won = "UndergroundRivalWinText",
    },
  },
  YELLOW_FOREST = {
    [1] = {
      after = "YellowForestWalkerAfterText",
      battle = "YellowForestWalkerSeenText",
      range = 0,
      won = "YellowForestWalkerBeatenText",
    },
  },
}
