-- Writing the authoring out.
--
-- THERE ARE TWO DESTINATIONS AND THEY ARE NOT INTERCHANGEABLE.  This is the
-- single most important thing in this file, and it cost a day to learn:
--
--   1. THE PROFILE FILE.  `data/voxel_heights.lua`, dropped into the voxel
--      mod's own install.  The mod reads it through `V.data`, which is
--      `mod:read(rel)` on the mod's OWN path and nothing else -- so this
--      works, and it works because the player's save directory shadows the
--      game folder file by file.  It is the right export for your own
--      install and for a fork.
--
--   2. THE PROFILE PACK.  A separate mod, for other people.  A pack that
--      shipped its own `data/voxel_heights.lua` would install cleanly and
--      DO NOTHING: `V.data` never consults the loader, the asset override
--      path is gated to `assets/generated/` and reaches no mod's data
--      directory, and there is no merge hook.  So the pack states its pins
--      the way the runtime actually reads them from a second mod --
--      `map.def.voxelClassPins`, which TileShape.at reads per lookup and
--      which OUTRANKS the profile's own pins -- and patches every map drawn
--      with the tileset.  A pin says what a DRAWING is, so it belongs to
--      the tileset; the runtime reads it off the map, so it has to be laid
--      on each one.  A pack that only carried the maps someone happened to
--      open leaves the same tree resolving as a wall everywhere else.
--
-- The pack ALSO carries data/voxel_heights.lua, for a reader who wants to
-- fold it into a fork by hand.  It is documentation there, not machinery,
-- and the README says so.
--
-- NO CARTRIDGE BYTES LEAVE HERE.  Pins are numbers and class names; not one
-- tile of art, not one palette, not one block table is written.

local Serialize = require("core.Serialize")
local Shape = require("core.Shape")
local Cache = require("core.Cache")
local Zip = require("core.Zip")
local Grid = require("core.Grid")
local Doc = require("core.Doc")

local Export = {}

-- 2 adds side-face art (`bands`) beside the per-texel heights, and
-- reshapes each tileset entry to name which of the two it carries.
Export.SIDECAR_VERSION = 2

-- The sidecar's keys are prefixed so they can NEVER be read as a class pin.
-- `authoredGroups` walks the whole entry and acts on any key that is a
-- class name with an array value; a sidecar key named `table` or `post`
-- would be swallowed as a tile list.  `vte_` is not a class and never will
-- be, and TileShape drops what it does not recognise rather than raising --
-- which is exactly what makes an extension safe here.
Export.SIDECAR_PREFIX = "vte_"

local HEADER = [[
-- Voxel shape profile -- generated by the Voxel Tileset Editor.
--
-- PRESENTATION ONLY.  Every entry below decides how a tile is DRAWN in
-- voxel mode.  Collision, warps, triggers, movement and saves read the same
-- data they always did; nothing here can move a wall the player walks into.
--
-- Nothing below is extracted, derived or copied from a cartridge: it is
-- tile id numbers and class names, hand-authored against art the reader
-- already owns.
--
]]

-- ------------------------------------------------------------ the profile

-- The merged profile as Lua source, ready to be dropped in beside the mod's
-- own.  `opts.full` writes the whole profile (a drop-in replacement);
-- otherwise only the tilesets this document touched are written, which is
-- the file to read when you want to see what you changed.
function Export.profileLua(bridge, doc, opts)
  opts = opts or {}
  local merged = Shape.mergeProfile(bridge, doc)
  local out = merged

  if not opts.full then
    out = { version = merged.version, tilesets = {} }
    for id, e in pairs(doc.tilesets or {}) do
      if not Doc.isEmpty(e) then out.tilesets[id] = merged.tilesets[id] end
    end
  end

  local sidecar = Export.sculptSidecar(doc)
  if sidecar then
    for id, entry in pairs(out.tilesets or {}) do
      local s = sidecar.tilesets[id]
      if s then
        -- the prefix is what keeps these out of the class-pin namespace: a
        -- host reading this profile sees keys it does not know and skips
        -- them, which is the documented contract for unknown keys
        if s.sculpt then entry[Export.SIDECAR_PREFIX .. "sculpt"] = s.sculpt end
        if s.bands then entry[Export.SIDECAR_PREFIX .. "bands"] = s.bands end
        entry[Export.SIDECAR_PREFIX .. "version"] = Export.SIDECAR_VERSION
      end
    end
    out[Export.SIDECAR_PREFIX .. "hash"] = sidecar.hash
  end

  local body = HEADER
  if not opts.full then
    body = body .. "-- This file lists ONLY the tilesets this authoring touched.  It is a\n"
        .. "-- partial profile: merge it into the mod's own, or export the full\n"
        .. "-- profile if you want a drop-in replacement.\n--\n"
  end
  body = body .. "-- profile hash: " .. Serialize.hash(out) .. "\n\n"
  return body .. "local profile = " .. Serialize.value(out) .. "\n\nreturn profile\n"
end

-- ------------------------------------------------------------ the sidecar

-- Per-tile height maps, versioned and hashed.
--
-- HASHED SO A MESH CACHE CAN TELL.  The voxel mod keeps baked geometry on
-- disk and serves it back on a later run; geometry built from an older
-- sculpt is indistinguishable from correct geometry unless something in
-- the file says which sculpt it came from.  The hash is that something.
-- SIDE-FACE ART RIDES HERE TOO, and for the same reason sculpts do.
--
-- A pin, a fold, a class height and a place edit are all things the shipped
-- mod already reads.  A per-band source tile is not: nothing in TileShape or
-- ChunkMesher looks for one, and inventing a key in `voxel_heights.lua` that
-- the runtime ignores would be a file that installs cleanly and does nothing,
-- which this project has already got wrong once.  So it goes in the versioned
-- sidecar -- a mesher that wants it can read it, one that does not is
-- unaffected, and the README says which is which.
function Export.sculptSidecar(doc)
  local any = false
  local out = { version = Export.SIDECAR_VERSION, tilesets = {} }
  for id, e in pairs(doc.tilesets or {}) do
    local hasS = next(e.sculpt or {}) ~= nil
    local hasB = next(e.bands or {}) ~= nil
    if hasS or hasB then
      any = true
      local t = {}
      if hasS then
        local sc = {}
        for tile, s in pairs(e.sculpt) do
          sc[tile] = { res = s.res, h = s.h }
        end
        t.sculpt = sc
      end
      if hasB then
        local bd = {}
        for tile, b in pairs(e.bands) do
          local one = {}
          for band, src in pairs(b) do one[band] = src end
          bd[tile] = one
        end
        t.bands = bd
      end
      out.tilesets[id] = t
    end
  end
  if not any then return nil end
  out.hash = Serialize.hash(out.tilesets)
  return out
end

-- A sculpt is consumed per COORDINATE, not per tile: ChunkMesher's sub-tile
-- branch reads `shape.sub`, and a shape only carries one when
-- `map.def.voxelTileEdits["tx,ty"]` put it there.  So a pack that wants
-- sculpts to show has to name every square the tile is drawn on.
--
-- THE COST IS REAL AND IT IS THE READER'S TO SPEND -- at res 8 one tile is
-- up to 64 boxes, and a common ground tile appears thousands of times.  So
-- this is capped, opt-in, and it reports what it left out rather than
-- quietly truncating.
function Export.expandSculpts(cache, doc, tsId, cap)
  cap = cap or 4000
  local e = doc.tilesets[tsId]
  if not (e and next(e.sculpt or {})) then return nil end
  local ts = cache.tilesets[tsId]
  if not ts then return nil, "tileset not in this cache" end
  local blocks = ts.blocks or {}
  local blockTiles = ts.blockTiles or 4
  local gen3 = tonumber(ts.blockTiles) == 2 and tonumber(ts.blockCells) == 1
  local wanted = {}
  for tile in pairs(e.sculpt) do wanted[tile] = true end

  local out, total, dropped = {}, 0, 0
  for _, mapId in ipairs(Cache.mapsUsing(cache, tsId)) do
    local def = Cache.map(cache, mapId)
    if def and def.width then
      -- the SAME reader the editor's own window uses -- a Gen 3 map stores
      -- its grid as a binary string and reading it as an array finds nothing
      local readBlock = Grid.blockReader(def, ts)
      local edits = {}
      for by = 0, (def.height or 0) - 1 do
        for bx = 0, def.width - 1 do
          local b = readBlock(bx, by)
          if b then
            if gen3 then
              for q = 0, 3 do
                local tile = b * 4 + q
                if wanted[tile] then
                  local tx = bx * 2 + (q % 2)
                  local ty = by * 2 + math.floor(q / 2)
                  if total < cap then
                    local s = e.sculpt[tile]
                    edits[tx .. "," .. ty] = { sub = { res = s.res, h = s.h } }
                    total = total + 1
                  else
                    dropped = dropped + 1
                  end
                end
              end
            else
              local blk = blocks[b + 1]
              if blk then
                for j = 0, blockTiles - 1 do
                  for i = 0, blockTiles - 1 do
                    local tile = blk[j * blockTiles + i + 1]
                    if tile and wanted[tile] then
                      local tx = bx * blockTiles + i
                      local ty = by * blockTiles + j
                      if total < cap then
                        local s = e.sculpt[tile]
                        edits[tx .. "," .. ty] = { sub = { res = s.res, h = s.h } }
                        total = total + 1
                      else
                        dropped = dropped + 1
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      if next(edits) then out[mapId] = edits end
    end
  end
  return out, nil, { written = total, dropped = dropped, cap = cap }
end

-- --------------------------------------------------------------- the pack

local function jsonString(s)
  s = tostring(s)
  s = s:gsub("\\", "\\\\")
  s = s:gsub('"', '\\"')
  s = s:gsub("\n", "\\n")
  s = s:gsub("\r", "")
  return '"' .. s .. '"'
end

function Export.manifest(doc, opts)
  opts = opts or {}
  local lines = {
    '  "id": ' .. jsonString(doc.id),
    '  "name": ' .. jsonString(doc.name),
    '  "version": ' .. jsonString(doc.modVersion or "1.0.0"),
    '  "api": 2',
    '  "entry": "main.lua"',
    '  "profile": "content"',
    '  "category": "GRAPHICS"',
    '  "priority": ' .. tostring(opts.priority or 150),
    '  "game_version": ' .. jsonString(opts.gameVersion or ">=0.1.37 <2.0.0"),
    '  "dependencies": [' .. jsonString(opts.dependsOn or "DRAMATIC_SHAPE") .. ']',
    '  "optional_dependencies": []',
    '  "conflicts": []',
    '  "affects_link": false',
    '  "update_check": false',
    '  "description": ' .. jsonString(
        "Voxel shape pins only. Presentational: it changes how tiles are "
        .. "drawn in voxel mode and nothing else -- collision, warps, "
        .. "triggers and saves are untouched. Requires the Dramatic Shape "
        .. "voxel mod; contains no cartridge art."),
  }
  return "{\n" .. table.concat(lines, ",\n") .. "\n}\n"
end

-- The pack's entry point, generated.
--
-- PATCH, NOT REGISTER: these maps already exist, and registering over one
-- replaces it wholesale -- including every field this editor never touched
-- and another mod may have changed.  Each patch is its own pcall so one
-- map the player's cartridge does not have costs that map and not the pack.
function Export.packMain(doc, plan, opts)
  opts = opts or {}
  local b = {}
  local function w(s) b[#b + 1] = s end

  w("-- " .. doc.name .. " -- voxel shape pins.")
  w("--")
  w("-- Generated by the Voxel Tileset Editor.  PRESENTATION ONLY: every")
  w("-- statement below decides how a tile is DRAWN in voxel mode.  Nothing")
  w("-- here touches collision, movement, warps, scripts or saves.")
  w("--")
  w("-- HOW THE PINS REACH THE RENDERER.  A pin says what a DRAWING is, so")
  w("-- it belongs to the tileset -- but the voxel mod reads pins off the")
  w("-- MAP (TileShape.at consults map.def.voxelClassPins on every lookup,")
  w("-- above its own profile and below a coordinate override), so they are")
  w("-- laid on every map drawn with that tileset.  The map's own pins win:")
  w("-- those are the reader's own decisions and this pack is a suggestion.")
  w("")
  w("local mod = ...")
  w("")
  w("-- tileset id -> { tile id -> class }")
  w("local PINS = " .. Serialize.value(plan.pins, ""))
  w("")
  w("-- map id -> tileset id, for every map this pack has something to say about")
  w("local MAPS = " .. Serialize.value(plan.maps, ""))
  w("")
  if plan.edits and next(plan.edits) then
    w("-- Per-coordinate sub-tile sculpts.  ChunkMesher's sub-tile branch")
    w("-- reads `shape.sub`, and a shape only carries one when a coordinate")
    w("-- override puts it there -- so a sculpt is named square by square.")
    w("local EDITS = " .. Serialize.value(plan.edits, ""))
    w("")
  else
    w("local EDITS = {}")
    w("")
  end
  w([[
local function apply()
  local host = mod.find and mod.find("]] .. (opts.dependsOn or "DRAMATIC_SHAPE") .. [[")
  if not host then
    mod.log:warn("the voxel mod is not loaded; these pins have nothing to reach")
    return
  end

  local applied, skipped = 0, 0
  local ids = {}
  for mapId in pairs(MAPS) do ids[#ids + 1] = mapId end
  table.sort(ids)

  for _, mapId in ipairs(ids) do
    local tsId = MAPS[mapId]
    -- `false` means "this map is here for its own square-by-square edits and
    -- its tileset carries no pins" -- a real case, and indexing PINS with it
    -- has to answer nil rather than raise.
    local pins = tsId and PINS[tsId] or nil
    local edits = EDITS[mapId]
    if pins or edits then
      local ok = pcall(function()
        local def = mod.content.maps.get and mod.content.maps:get(mapId) or nil
        local merged = nil
        if pins then
          merged = {}
          for tile, class in pairs(pins) do merged[tile] = class end
          -- the map's own pins win
          local own = def and def.voxelClassPins
          if own then for tile, class in pairs(own) do merged[tile] = class end end
        end
        local patch = {}
        if merged then patch.voxelClassPins = merged end
        if edits then
          local e = {}
          for k, v in pairs(edits) do e[k] = v end
          local own = def and def.voxelTileEdits
          if own then for k, v in pairs(own) do e[k] = v end end
          patch.voxelTileEdits = e
        end
        mod.content.maps:patch(mapId, patch)
      end)
      if ok then applied = applied + 1 else skipped = skipped + 1 end
    end
  end

  -- The resolver caches per tileset; the pins above are read per lookup and
  -- need no invalidation, but a host that has already resolved a tileset
  -- with its own profile should re-resolve so class heights match.
  local lib = host.exports and host.exports.lib
  if lib and lib.require then
    local okTS, TS = pcall(lib.require, "TileShape")
    if okTS and type(TS) == "table" and TS.invalidate then pcall(TS.invalidate) end
  end

  mod.log:info("voxel pins applied to %d map(s), %d skipped", applied, skipped)
end

apply()
]])
  return table.concat(b, "\n")
end

function Export.readme(doc, plan, opts)
  local L = {}
  local function w(s) L[#L + 1] = s end
  w("# " .. doc.name)
  w("")
  w("Voxel shape pins for the Dramatic Shape voxel mod.")
  w("")
  w("**Presentation only.** Every statement in this pack decides how a tile is")
  w("*drawn* in voxel mode. Collision, movement, warps, triggers and saves read")
  w("exactly the data they always did. A stairwell cell is still the walkable")
  w("warp cell it was when it was flat.")
  w("")
  w("**No cartridge art.** The pack is tile id numbers and class names. It")
  w("contains no tileset image, no palette and no block table, and it will not")
  w("work without your own copy of the game and its extracted cache.")
  w("")
  w("## Install")
  w("")
  w("1. Install the Dramatic Shape voxel mod first -- this pack depends on it.")
  w("2. Drop this folder into `mods/`.")
  w("3. Enable it in the mod manager. It loads after the voxel mod (priority "
    .. tostring(opts and opts.priority or 150) .. ").")
  w("")
  w("## What is in it")
  w("")
  local tsIds = {}
  for id in pairs(plan.pins) do tsIds[#tsIds + 1] = id end
  table.sort(tsIds)
  for _, id in ipairs(tsIds) do
    local n = 0
    for _ in pairs(plan.pins[id]) do n = n + 1 end
    w("- `" .. id .. "`: " .. n .. " tile pin" .. (n == 1 and "" or "s"))
  end
  local nMaps = 0
  for _ in pairs(plan.maps) do nMaps = nMaps + 1 end
  w("")
  w("Applied to " .. nMaps .. " map" .. (nMaps == 1 and "" or "s") .. ".")
  w("")
  w("`data/voxel_heights.lua` is included for reading, not for loading: a mod")
  w("can only read its own `data/` directory, so that file is what to merge")
  w("into a fork of the voxel mod by hand. The pins that actually take effect")
  w("are the ones in `main.lua`.")
  w("")
  if plan.sculptNote then w(plan.sculptNote) w("") end
  w("Missing fields are ignored and unknown classes fall through to the voxel")
  w("mod's own detection, so an older host loads this pack without complaint.")
  w("")
  return table.concat(L, "\n")
end

-- Everything the pack needs, worked out once so the UI can show it before
-- anyone commits to writing a file.
function Export.plan(bridge, doc, caches, opts)
  opts = opts or {}
  local plan = { pins = {}, maps = {}, edits = {}, notes = {},
                 counts = { pins = 0, maps = 0, places = 0 } }
  local vocab = Shape.vocabulary(bridge)

  for tsId, e in pairs(doc.tilesets or {}) do
    if not Doc.isEmpty(e) then
      local pins = {}
      local n = 0
      for tile, class in pairs(e.pins or {}) do
        if vocab[class] then pins[tile] = class n = n + 1 end
      end
      if n > 0 then plan.pins[tsId] = pins end

      for _, c in ipairs(caches) do
        if c.tilesets[tsId] then
          for _, mapId in ipairs(Cache.mapsUsing(c, tsId)) do
            plan.maps[mapId] = tsId
          end
          if opts.sculpts and next(e.sculpt or {}) then
            local edits, err, stats = Export.expandSculpts(c, doc, tsId, opts.sculptCap)
            if edits then
              for mapId, t in pairs(edits) do plan.edits[mapId] = t end
              if stats and stats.dropped > 0 then
                plan.notes[#plan.notes + 1] =
                  ("%s: %d sculpt placements written, %d left out at the %d cap")
                  :format(tsId, stats.written, stats.dropped, stats.cap)
              end
            elseif err then
              plan.notes[#plan.notes + 1] = tsId .. ": " .. err
            end
          end
          break
        end
      end
    end
  end

  -- Any map named by a place edit is a map the pack has something to say
  -- about, whether or not its tileset carries a pin.
  -- PLACE EDITS ALWAYS SHIP.  A per-texel sculpt is expensive and opt-in;
  -- naming one square of one map is a deliberate statement about that square
  -- and there is no version of "export my work" that leaves it out.  They go
  -- into the same `voxelTileEdits` table the sculpt expansion writes, and the
  -- reader's own entries win where both name the same square.
  local places = 0
  for mapId, m in pairs(doc.maps or {}) do
    for k, o in pairs(m.tiles or {}) do
      local clean = {}
      if type(o.art) == "string" then clean.art = o.art end
      if type(o.h) == "number" then clean.h = o.h end
      if type(o.fold) == "string" then clean.fold = o.fold end
      if type(o.sub) == "table" and o.sub.res and o.sub.h then
        clean.sub = { res = o.sub.res, h = o.sub.h }
      end
      if next(clean) then
        plan.edits[mapId] = plan.edits[mapId] or {}
        plan.edits[mapId][k] = clean
        plan.maps[mapId] = plan.maps[mapId] or false
        places = places + 1
      end
    end
  end
  if places > 0 then
    plan.notes[#plan.notes + 1] =
      ("%d square(s) named individually across %d map(s)")
      :format(places, (function()
        local n = 0
        for _ in pairs(doc.maps or {}) do n = n + 1 end
        return n
      end)())
  end
  plan.counts.places = places

  if opts.sculpts then
    plan.sculptNote =
      "Per-texel sculpts are shipped as coordinate overrides, one entry per"
      .. " square the sculpted tile is drawn on. They are the expensive part"
      .. " of this pack; a host that does not understand them ignores them."
  end

  local np, nm = 0, 0
  for _, t in pairs(plan.pins) do for _ in pairs(t) do np = np + 1 end end
  for _ in pairs(plan.maps) do nm = nm + 1 end
  plan.counts.pins = np
  plan.counts.maps = nm
  return plan
end

function Export.pack(bridge, doc, caches, opts)
  opts = opts or {}
  local plan = Export.plan(bridge, doc, caches, opts)
  local files = {
    { name = "manifest.json", data = Export.manifest(doc, opts) },
    { name = "main.lua", data = Export.packMain(doc, plan, opts) },
    { name = "README.md", data = Export.readme(doc, plan, opts) },
    { name = "data/voxel_heights.lua",
      data = Export.profileLua(bridge, doc, { full = false }) },
  }
  local sidecar = Export.sculptSidecar(doc)
  if sidecar then
    files[#files + 1] = {
      name = "data/voxel_sculpts.lua",
      data = "-- Per-texel height maps and side-face art, version "
          .. Export.SIDECAR_VERSION
          .. ", hash " .. sidecar.hash .. ".\n"
          .. "-- A host that does not read this file is not missing anything it\n"
          .. "-- needs: the pins in main.lua stand on their own.\n\n"
          .. "return " .. Serialize.value(sidecar) .. "\n",
    }
  end
  return Zip.build(files), plan, files
end

return Export
