-- Generated by tools/build_data.py. DO NOT EDIT.
-- Source: Gen2 Phase 2B symbol-derived trainer text scaffold
return {
  AZALEA_TOWN = {
    [1] = {
      after = "AzaleaTownRivalAfterText",
      battle = "AzaleaTownRivalBeforeText",
      range = 0,
      won = "AzaleaTownRivalWinText",
    },
  },
  RADIO_TOWER5_F = {
    [1] = {
      after = "RadioTower5FRocketBossAfterText",
      battle = "RadioTower5FRocketBossBeforeText",
      range = 0,
      won = "RadioTower5FRocketBossWinText",
    },
  },
  ROUTE24 = {
    [1] = {
      battle = "Route24RocketSeenText",
      range = 0,
      won = "Route24RocketBeatenText",
    },
  },
  ROUTE32 = {
    [1] = {
      after = "Route32UnusedFisher1AfterText",
      battle = "Route32UnusedFisher1SeenText",
      range = 0,
      won = "Route32UnusedFisher1BeatenText",
    },
    [2] = {
      after = "Route32UnusedFisher2AfterText",
      battle = "Route32UnusedFisher2SeenText",
      range = 0,
      won = "Route32UnusedFisher2BeatenText",
    },
  },
  TRAINER_HOUSE_B1_F = {
    [1] = {
      battle = "TrainerHouseB1FCalBeforeText",
      range = 0,
      won = "TrainerHouseB1FCalBeatenText",
    },
  },
}
