local ROOT=(arg and arg[0] and arg[0]:match("^(.*[/\\])")) or "tests/";ROOT=ROOT:gsub("tests[/\\]$","")
local p,f=0,0;local function ck(v,m) if v then p=p+1;print('PASS '..m) else f=f+1;print('FAIL '..m) end end
local cfg={tornado={enabled=true,everySeconds=99999,maxActive=3,formationSeconds=8,roamSeconds=180,ropeSeconds=12,carryChance=.1,touchRadius=14,waterTwister=true,funnel=true,funnelSeconds=2.5,sandstorms=false}}
local Settings={is=function(k,v) return k=='tornado' and v=='on' end,tornadoPickupChance=function() return 1 end,weatherDisabled=function() return false end};local WS={level=1,current=function() return {id='GALE'} end}
local player={cellX=2,cellY=2,px=32,py=32,facing='down',surfing=false};local current='ROUTE_1'
local defs={ROUTE_1={id='ROUTE_1',outdoor=true,tileset='OVERWORLD',width=8,height=8,connections={right={map='PALLET',offset=0}},warps={}},PALLET={id='PALLET',outdoor=true,tileset='OVERWORLD',width=8,height=8,connections={left={map='ROUTE_1',offset=0}},warps={}}}
local map={id=current,widthCells=8,heightCells=8,def=defs[current]};function map:isWaterCell() return false end
local ow={map=map,player=player,camera={x=0,y=0}};function ow:partyKnows() return false end
local Scene={now={visible='world',indoors=false,outdoor=true,mapId=current,playerPosKnown=true,playerWorldX=32,playerWorldY=32},overworld=function() return ow end}
local game={save={visited={ROUTE_1=true,PALLET=true}},data={maps=defs,field={outsideTilesets={OVERWORLD=true},tilesets={OVERWORLD={}},flyWarps={}}}}
local Map={};function Map.isOutside(d) return d.outdoor end;function Map.isOutdoor(d) return d.outdoor end;function Map.defIsWaterCell() return false end;function Map.defPassable(d,ts,x,y) return x>=0 and y>=0 and x<d.width and y<d.height end;Map.defIsWalkableCell=Map.defPassable;package.preload['src.world.Map']=function() return Map end
local Flat={ready=function() return true end,sampleAt=function(x,z,o) o=o or {};o.water=false;o.solid=false;o.groundY=0;return o end};local Bridge={presentation3d=function() return true end,active=function() return true end};local Wind={direction=function() return 1,0 end};local Funnel={active=false,update=function() end,stop=function() end}
local save,warps,opts={},0,nil;local world={};function world:warpTo(dest,x,y,face,o) warps=warps+1;opts=o;current=dest;Scene.now.mapId=dest;Scene.now.playerWorldX=x*16;Scene.now.playerWorldY=y*16;player.cellX,player.cellY,player.px,player.py=x,y,x*16,y*16;map={id=dest,widthCells=8,heightCells=8,def=defs[dest]};function map:isWaterCell() return false end;ow.map=map;if o and o.onDone then o.onDone() end;return true end
local mod={game=game,world=world,save={set=function(self,k,v) save[k]=v end,get=function(self,k,d) local v=save[k];if v==nil then return d end;return v end},log={info=function() end,warn=function() end}};local V={mod=mod}
function V.require(n) local m={Config={get=function() return cfg end},Settings=Settings,Scene=Scene,Funnel=Funnel,WeatherState=WS,VoxelAtmosBridge=Bridge,FlatWorldInteraction=Flat,WindEngine=Wind};if m[n] then return m[n] end error(n) end
love={math={random=function() return .25 end}};local T=assert(loadfile(ROOT..'lib/Tornado.lua'))(V);T._setRandom(function() return .25 end)
local l=T.landingFor('PALLET');ck(l and l.source=='connection' and l.x>0 and l.y>0,'visited outdoor map derives safe connected landing');ck(l and T.validateLanding('PALLET',l.x,l.y,'land')==true,'derived landing passes escape proof')
T._gale=true;T.nextSpawn=1e9;local r={id=1,x=32,z=32,mapId='ROUTE_1',age=9,roamAge=0,formation=8,roamFor=180,ropeFor=12,stage='roam',ropeAge=0,seeker=false,destination=nil,heading=0,speed=0,spin=4.5,waterBlend=0,groundY=0,wander=0,seekAge=0};T.active={r};T.update(.05)
ck(r.stage=='pickup' and r.contactCarry==true,'walking into ordinary 3D funnel starts pickup');local stages={[r.stage]=true};for _=1,70 do T.update(.25);stages[r.stage]=true;if r.stage=='rope' then break end end
ck(stages.depart and stages.transfer and stages.arrival and stages.landing,'3D carry traverses depart/transfer/arrival/landing');ck(warps==1 and current=='PALLET','3D tornado changes actual map once');ck(opts and type(opts.onDone)=='function','public warp completion callback used');ck(r.stage=='rope' and not T.isCarrying(),'player set down before rope-out')
current='ROUTE_1';Scene.now.mapId=current;Scene.now.playerWorldX=160;Scene.now.playerWorldY=160;player.px,player.py=160,160
local wm={id='ROUTE_1',widthCells=16,heightCells=16,def={widthCells=16,heightCells=16}};function wm:isWaterCell(x,y) return x==2 and y==2 end;T.observeVoxelState({map=wm,neighbors={},player={px=160,py=160,cellX=10,cellY=10,facing='down'}})
local w={id=2,x=32,z=32,mapId='ROUTE_1',age=9,roamAge=0,formation=8,roamFor=180,ropeFor=12,stage='roam',ropeAge=0,seeker=false,destination=nil,heading=0,speed=0,spin=4.5,waterBlend=0,groundY=0,wander=0,seekAge=0};T.active={w};T._carry=nil;T._gale=true;T.nextSpawn=1e9;T.update(.25);ck(w.waterSurface and w.waterBlend>.5,'live water tile rapidly enables waterspout state')
print(('tornado relocation 8.1.58: %d passed, %d failed'):format(p,f));os.exit(f==0 and 0 or 1)
